sudo: false
language: ruby
script:
- |
  stat=0
  for projfile in $(ls configs/projects/[a-z]*.rb); do
    for plat in el-7-x86_64 ubuntu-18.04-amd64 osx-10.13-x86_64 windows-2012r2-x64; do
      proj=$(basename -s .rb $projfile)
      echo Inspecting ${proj} on ${plat}
      if ! bundle exec inspect $proj $plat | jq '.[].name' ; then
        stat=1
      fi
    done
  done
  # fail this step if there were any failures
  if [ $stat -eq 1 ]; then
    false
  fi
notifications:
  email: false
